version: '2'

services:
  mongodb:
    image: mongo:latest # use the latest image.
    container_name: mongodbforweather
    restart: always
    environment: # set required env variables to access mongo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '7000:27017' # en el puerto 7000 de mi máquina mapeame 27017
    volumes: # optional to preserve database after container is deleted.
      - ./mongodbforweather:/data/db
    
    # redis:
    #     image: redis
    #     container_name: weather-api-redis
    #     ports:
    #         - 6379:6379
    #     entrypoint: redis-server --appendonly yes
    #     restart: always

